apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agile-app.fullname" . }}-frontend
  labels:
    {{- include "agile-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "agile-app.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "agile-app.fullname" . }}-frontend
    spec:
      {{- if .Values.imagePullSecretName }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecretName }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}