{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agile-app.fullname" . }}-fe-ingress
  annotations:
    {{- if .Values.frontend.ingress.annotations }}
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.frontend.ingress.className }}
  ingressClassName: {{ .Values.frontend.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.frontend.ingress.enabled }}
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "agile-app.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.frontend.ingress.tls }}
  tls:
    {{- toYaml .Values.frontend.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}

---

{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "agile-app.fullname" . }}-be-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.backend.ingress.annotations }}
    {{- toYaml .Values.backend.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.backend.ingress.enabled }}
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "agile-app.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
          {{- end }}
    {{- end }}
    {{- end }}
  {{- if .Values.backend.ingress.tls }}
  tls:
    {{- toYaml .Values.backend.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}