{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agile-app.fullname" . }}-redis
  labels:
    {{- include "agile-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "agile-app.fullname" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "agile-app.fullname" . }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - containerPort: 6379
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- if .Values.redis.password }}
          env:
            - name: REDIS_PASSWORD
              value: "{{ .Values.redis.password }}"
          command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
          {{- end }}
          volumeMounts:
            {{- if .Values.redis.persistence.enabled }}
            - name: redis-data
              mountPath: /data
            {{- end }}
      volumes:
        {{- if .Values.redis.persistence.enabled }}
        - name: redis-data
          persistentVolumeClaim:
            claimName: {{ include "agile-app.fullname" . }}-redis-pvc
        {{- end }}
{{- end }} 