# Default values for agile-app Helm chart

# uncomment if to be used
# imagePullSecretName: mysecret

frontend:
  image:
    repository: your-frontend-image
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    NUXT_PUBLIC_WS_URL: ws://localhost:3001  # Default WebSocket URL for Nuxt runtimeConfig
    NUXT_PUBLIC_GOTO_BASE_URL: https://www.google.com/search?q=  # Default for the "Go to" button
  resources: {}
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - host: frontend.local
        paths:
          - /
    tls: []

backend:
  image:
    repository: your-backend-image
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
    # nodePort: 32001  # Optional: only used if type is NodePort
  env:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    PORT: 3000
    # REDIS_PASSWORD: ""
    # OLLAMA_URL: "http://ollama:11434" # If using internal Ollama
  resources: {}
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/use-http2: "false"
    hosts:
      - host: backend.local
        paths:
          - /
    tls: []

redis:
  enabled: true
  image:
    repository: redis
    tag: 7-alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  persistence:
    enabled: false
    size: 1Gi
    storageClass: ""
  resources: {}
  password: ""

ollama:
  enabled: false
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 11434
  resources: {}
  env: {}

nodeSelector: {}
tolerations: []
affinity: {}